### ISSUE TITLE
Windows Protect

### ISSUE THREAD

**Issue by JustHxnry** [baconcowa/Overlay-Anywhere#2]
Hello, I just downloaded program and got this message ( https://i.imgur.com/BQ0uIMh.png ).
I just have to ask if in this program are some viruses / malware. 

Thanks,
Have a nice day

**Comment by JustHxnry** [comment]
Note: on VirusTotal zero issues foubd

**Comment by baconcowa** [comment]
A little background: Microsoft Defender always ask you to think twice before you run an app that is from a publisher that is not know to their database. The pop-up tries to make sure you know what you are opening. 

I did not add any virus code in to the program and did not try to. Since I have already open sourced this program, you can check the code yourself if you are still worried or even build the program with the source code to make sure I did not have changed the executable file.

Note: This program is no longer under active development because of the heavy workload in our university. I did plan for continuing this project in the future, but it would be several years later (if the Discord Overlay still only works for DirectX windows)

**Comment by JustHxnry** [comment]
Okay. Im closing issue
